# Generated by Django 2.1.1 on 2018-11-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_tab_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='orders',
            field=models.ManyToManyField(blank=True, to='ordering.Order'),
        ),
    ]
