# Generated by Django 2.1.1 on 2018-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_auto_20181108_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unity_price',
            field=models.PositiveSmallIntegerField(default=0.0),
        ),
    ]
