# Generated by Django 2.1.1 on 2018-11-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_auto_20181113_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unity_price',
            field=models.FloatField(default=0.0),
        ),
    ]
