# Generated by Django 2.1.1 on 2018-11-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_auto_20181113_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab',
            name='orders',
        ),
    ]
